name: Run scrapers

on:
  schedule:
    - cron:  '*/5 * * * *'

jobs:
  run_scraper:

    runs-on: ubuntu-latest
    continue-on-error: true
    timeout-minutes: 10
    strategy:
      matrix:
        python-version: [3.7]
        canton:
          - AG
          - AI
          - AR
          - BE
          - BS
          - FR
          - GL
          - GR
          - JU
          - LU
          - NE
          - NW
          - OW
          - SG
          - SH
          - SO
          - SZ
          - TG
          - TI
          - UR
          - VD
          - VS
          - ZG
        overwrite: [yes]
        include:
          - python-version: 3.7
            canton: AG
            overwrite: no

          - python-version: 3.7
            canton: AI
            source: https://www.ai.ch/themen/gesundheit-alter-und-soziales/gesundheitsfoerderung-und-praevention/uebertragbare-krankheiten/coronavirus
            overwrite: no

          - python-version: 3.7
            canton: AR
            source: https://www.ar.ch/verwaltung/departement-gesundheit-und-soziales/amt-fuer-gesundheit/informationsseite-coronavirus/
            overwrite: no

          - python-version: 3.7
            canton: BE
            overwrite: no

          - python-version: 3.7
            canton: BS
            overwrite: no

          - python-version: 3.7
            canton: LU
            source: https://gesundheit.lu.ch/themen/Humanmedizin/Infektionskrankheiten/Coronavirus
            overwrite: no

          - python-version: 3.7
            canton: OW
            source: https://www.ow.ch/de/verwaltung/dienstleistungen/?dienst_id=5962
            overwrite: no

          - python-version: 3.7
            canton: SG
            overwrite: no

          - python-version: 3.7
            canton: TG
            source: https://www.tg.ch/news/fachdossier-coronavirus.html/10552
            overwrite: no

          - python-version: 3.7
            canton: UR
            overwrite: no

          - python-version: 3.7
            canton: VD
            source: https://www.vd.ch/toutes-les-actualites/hotline-et-informations-sur-le-coronavirus/point-de-situation-statistique-dans-le-canton-de-vaud/

          - python-version: 3.7
            canton: ZG
            source: https://www.zg.ch/behoerden/gesundheitsdirektion/statistikfachstelle/themen/gesundheit/corona

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - run: npm ci
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        sudo apt-get install sqlite3 poppler-utils

    - name: Scrape new data
      env:
        SCRAPER_KEY: ${{ matrix.canton }}
        SCRAPER_SOURCE: ${{ matrix.source }}
        SCRAPER_OVERWRITE: ${{ matrix.overwrite }}
      run: |
        ./scrapers/run_scraper.sh
    
    - name: Commit and push to repo
      uses: github-actions-x/commit@v2.6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        push-branch: master
        name: GitHub Action Scraper
        email: scraper@open.zh.ch
        commit-message: Update COVID19_Fallzahlen_Kanton_${{ matrix.canton }}_total.csv from scraper
        rebase: 'true'
